BestRestaurant/Models/BestRestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurant.Models
{
  public class BestRestaurantContext : DbContext
  {
    public virtual DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }

    public BestRestaurantContext(DbContextOptions options) : base(options) { }
  }
}

BestRestaurant/Models/Cuisine.cs
using MySql.Data.MySqlClient;
using System.Collections.Generic;
using System;

namespace BestRestaurant.Models
{
  public class Cuisine
  {
    public int CuisineId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }
  }
}

BestRestaurant/Models/Restaurant.cs
using System.Collections.Generic;

namespace BestRestaurant.Models
{
  public class Restaurant
  {
    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public int CuisineId { get; set; }
    public virtual Cuisine Cuisine { get; set; }
  }
}

BestRestaurant/Controllers/CuisineController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantContext _db;
    public CuisinesController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id);
      thisCuisine.Restaurants = _db.Restaurants.Where(restaurant => restaurant.CuisineId == id).ToList();
      return View(thisCuisine);
    }

    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisines => cuisines.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurant/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurant.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

BestRestaurant/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BestRestaurant.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurant.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly BestRestaurantContext _db;
    public RestaurantsController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurant => restaurant.Cuisine).ToList();
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(model);
    }
    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);
    }
    public ActionResult Edit(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(thisRestaurant);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      return View(thisRestaurant);

    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurants => restaurants.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


  }
}

BestRestaurant/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine;
<h4>Add a new Cuisine</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    <input type="submit" value="Add Cuisine" />
}

<p>@Html.ActionLink("Back to Cuisine", "Index")</p>
<p>@Html.ActionLink("All Restaurants", "Index", "Restaurants")</p>

BestRestaurant/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

BestRestaurant/Views/Cuisines/Details.cshtml
 @{
  Layout = "_Layout";
}
@using BestRestaurant.Models;
@model BestRestaurant.Models.Cuisine

<h2>Cuisine Details</h2> 
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>


@foreach (Restaurant restaurant in Model.Restaurants)
{
  <p>@Html.ActionLink($"{restaurant.Name}", "Details", "Restaurants", new { id = restaurant.RestaurantId})</p>
}

<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId})</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Cuisine

<h2>Edit</h2>

<h4>Edit this cusine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CuisineId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
@model List<BestRestaurant.Models.Cuisine>;

<h1>Cuisines</h1>

@foreach(Cuisine cuisine in Model)
{
  <p>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</p>
}

<p>@Html.ActionLink("Add New Cuisine", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

BestRestaurant/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to your Cuisines</h1>

<h3>@Html.ActionLink("Cuisines", "Index", "Cuisines")</h3>
<h3>@Html.ActionLink("Restaurants", "Index", "Restaurants")</h3>

BestRestaurant/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant;
<h4>Add a new Restaurant</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <br>
    @Html.LabelFor(model => model.Address)
    @Html.TextBoxFor(model => model.Address)
    <br>
    @Html.LabelFor(model => model.Cuisine)
    @Html.DropDownList("CuisineId")
    <br>
    <input type="submit" value="Add new restautant" />
}

<p>@Html.ActionLink("Show all restaurent", "Index")</p>

BestRestaurant/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@Html.DisplayNameFor(model => model.Address): @Html.DisplayFor(model => model.Address)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

BestRestaurant/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h2>Restaurant Details</h2> 
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Address): @Html.DisplayFor(model => model.Address)<h3>
<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId})</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model BestRestaurant.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this restaurant: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RestaurantId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)
    @Html.LabelFor(model => model.Address)
    @Html.EditorFor(model => model.Address)

    @Html.LabelFor(model => model.Cuisine)
    @Html.DropDownList("CuisineId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurant/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurant.Models;
@model List<BestRestaurant.Models.Restaurant>;

<h1>Restaurants</h1>

@if (Model.Count == 0)
{
  <p>You have no restaurants to display!</p>
}

@foreach (Restaurant restaurant in Model)
{ 
  <p>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId}) | @Html.ActionLink($"{restaurant.Cuisine.Name}", "Details", "Cuisines", new { id = restaurant.CuisineId} )</p>   
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("New Restaurant", "Create")</p>

BestRestaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>To Do List</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="box">
      @RenderBody()
    </div>
  </body>
</html>